In [3]:
import numpy as np

In [4]:
np.__version__

'1.14.0'

In [5]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [6]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [7]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [8]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [11]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
np.random.random((3, 3)) # uniformly distributed values between 0 and 1

array([[0.28275459, 0.19562254, 0.73471249],
       [0.30019819, 0.03093609, 0.25635125],
       [0.78418236, 0.46909427, 0.141781  ]])

In [14]:
np.random.normal(0, 1, (3, 3)) # mean 0, std 1

array([[ 0.18478341,  0.45128733,  0.86261628],
       [-0.10448082,  0.29055719, -1.58122079],
       [ 0.4276976 , -1.1920843 , -0.10537029]])

In [15]:
np.random.randint(0, 10, (3, 3))

array([[5, 0, 8],
       [3, 2, 6],
       [2, 0, 9]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

In [18]:
x1

array([5, 0, 3, 3, 7, 9])

In [19]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype: int32
itemsize: 4 bytes
nbytes: 240 bytes


In [20]:
x2[0, 0] = 12
print(x1[0], x1[-1], x2[0, 0])

5 9 12


In [21]:
x = np.arange(10)
x[1:7:2]
x[5:1:-2]

array([5, 3])

In [22]:
x2[:, ::2] # all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [23]:
print(x2[0]) # equivalent to x2[0, :]

[12  5  2  4]


In [24]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[12  5]
 [ 7  6]]


In [25]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
x = np.array([1, 2, 3])
print(x.shape)
x = x.reshape((1, 3)) # row vector via reshape
print(x, x.shape)

(3,)
[[1 2 3]] (1, 3)


Join two numpy arrays

In [27]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = [99, 99, 99]
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [28]:
grid = np.array([[1, 2, 3], [4, 5, 6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [29]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [30]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7], [6, 5, 4]])

np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [31]:
y = np.array([[99], [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

Splitting arrays

In [32]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5]) # splitting points
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [33]:
grid = np.arange(16).reshape((4, 4))
print(grid)
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [34]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


Vectorized / Universal Functions

In [35]:
x = np.array([0, 1, 2, 3])
x + 5

array([5, 6, 7, 8])

In [36]:
theta = np.linspace(0, np.pi, 3)

print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [37]:
x = np.array([1, 2, 3])
print("x =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3, x))

x = [1 2 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]


In [38]:
x = np.array([1, 2, 4, 10])
print("x =", x)
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

x = [ 1  2  4 10]
ln(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [39]:
y = np.zeros(4, dtype='float32')
np.power(2, x, out=y)
print(y)

y = 2 ** x # creates temporary array with result, followed by copying values to y

[   2.    4.   16. 1024.]


In [40]:
x = np.arange(1, 6)
np.add.reduce(x)

15

In [41]:
np.multiply.reduce(x)

120

In [42]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [43]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

Aggregations

In [44]:
L = np.array([1, 2, 3])
np.sum(L)

6

In [45]:
print(np.min(L), np.max(L))
print(L.min(), L.max())

1 3
1 3


In [46]:
M = np.random.random((3, 4))
print(M)
M.min(axis=0) # The axis keyword specifies the dimension of the array that will be collapsed

[[0.65279032 0.63505887 0.99529957 0.58185033]
 [0.41436859 0.4746975  0.6235101  0.33800761]
 [0.67475232 0.31720174 0.77834548 0.94957105]]


array([0.41436859, 0.31720174, 0.6235101 , 0.33800761])

Boolean arrays

In [47]:
x = np.array([1, 2, 3, 4, 5])
print(x < 3, x != 3)

[ True  True False False False] [ True  True False  True  True]


In [48]:
np.sum(x < 6)

5

In [49]:
np.any(x > 8)

False

In [50]:
np.all(x == 6)

False

In [51]:
np.sum((x > 2) & (x < 5))

2

In [52]:
x[x < 5]

array([1, 2, 3, 4])

Fancy Indexing

In [53]:
x = np.arange(1, 20)
ind = [3, 7, 4]
x[ind]

array([4, 8, 5])

In [54]:
ind = np.array([[3, 7], [4, 5]])
x[ind]

array([[4, 8],
       [5, 6]])

In [55]:
x = np.arange(10)
i = np.array([2, 1, 8, 4])
x[i] = 99
print(x)

[ 0 99 99  3 99  5  6  7 99  9]


Sorting

In [56]:
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [57]:
x.sort()
print(x)

[1 2 3 4 5]


In [58]:
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)
print(i)

[1 0 3 2 4]
